// const data = [
//     {
//         id: 1,
//         latitude: 43.29399871826172,
//         longitude: 5.376543998718262,
//         image: "img/66993195266c203f1e457139.webp",
//         address: "Rue Paradis",
//         city: "Marseille",
//         date: "Ajoutée il y a 2 jours",
//         created_at: new Date("2026-05-03 14:32:18"),
//         quartier: "La Plaine",
//         cp: "13001",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "PENDING",
//         user_id: 1
//     },
//     {
//         id: 2,
//         latitude: 43.2965,
//         longitude: 5.3698,
//         image: "img/Imagecolle.png",
//         address: "Rue Sainte",
//         city: "Marseille",
//         date: "Ajoutée il y a 1 jour",
//         created_at: new Date("2026-05-02 10:12:00"),
//         quartier: "Vieux-Port",
//         cp: "13001",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 2
//     },
//     {
//         id: 3,
//         latitude: 43.2842,
//         longitude: 5.3700,
//         image: "img/rennes_boites_a_cles_sur_le_mobilier_urbain_large.jpg.webp",
//         address: "Avenue du Prado",
//         city: "Marseille",
//         date: "Ajoutée il y a 5 jours",
//         created_at: new Date("2026-04-29 09:45:00"),
//         quartier: "Prado",
//         cp: "13008",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 3
//     },
//     {
//         id: 4,
//         latitude: 43.3022,
//         longitude: 5.3811,
//         image: "img/66993195266c203f1e457139.webp",
//         address: "Cours Julien",
//         city: "Marseille",
//         date: "Ajoutée il y a 3 jours",
//         created_at: new Date("2026-05-01 15:00:00"),
//         quartier: "Cours Julien",
//         cp: "13006",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 4
//     },
//     {
//         id: 5,
//         latitude: 43.3100,
//         longitude: 5.4000,
//         image: "img/Imagecolle.png",
//         address: "Boulevard National",
//         city: "Marseille",
//         date: "Ajoutée il y a 6 jours",
//         created_at: new Date("2026-04-28 18:30:00"),
//         quartier: "Saint-Charles",
//         cp: "13003",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "PENDING",
//         user_id: 5
//     },
//     {
//         id: 6,
//         latitude: 43.2700,
//         longitude: 5.3900,
//         image: "img/rennes_boites_a_cles_sur_le_mobilier_urbain_large.jpg.webp",
//         address: "Rue d'Endoume",
//         city: "Marseille",
//         date: "Ajoutée il y a 4 jours",
//         created_at: new Date("2026-04-30 11:20:00"),
//         quartier: "Endoume",
//         cp: "13007",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 6
//     },
//     {
//         id: 7,
//         latitude: 43.3150,
//         longitude: 5.3650,
//         image: "img/66993195266c203f1e457139.webp",
//         address: "Rue Félix Pyat",
//         city: "Marseille",
//         date: "Ajoutée il y a 1 semaine",
//         created_at: new Date("2026-04-25 13:00:00"),
//         quartier: "Belle de Mai",
//         cp: "13003",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 7
//     },
//     {
//         id: 8,
//         latitude: 43.2500,
//         longitude: 5.4050,
//         image: "img/Imagecolle.png",
//         address: "Avenue de Mazargues",
//         city: "Marseille",
//         date: "Ajoutée il y a 2 semaines",
//         created_at: new Date("2026-04-20 08:40:00"),
//         quartier: "Mazargues",
//         cp: "13009",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 8
//     },
//     {
//         id: 9,
//         latitude: 43.29299871826172,
//         longitude: 5.375543998718262,
//         image: "img/rennes_boites_a_cles_sur_le_mobilier_urbain_large.jpg.webp",
//         address: "Boulevard Mirabeau 9",
//         city: "Marseille",
//         date: "Ajoutée il y a 1 semaine",
//         created_at: new Date("2026-03-01 14:32:18"),
//         quartier: "Mirabeau",
//         cp: "13100",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 9
//     },
//     {
//         id: 10,
//         latitude: 43.2980,
//         longitude: 5.4300,
//         image: "img/66993195266c203f1e457139.webp",
//         address: "Rue de Rome",
//         city: "Marseille",
//         date: "Ajoutée il y a 8 jours",
//         created_at: new Date("2026-04-24 12:00:00"),
//         quartier: "Castellane",
//         cp: "13006",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 10
//     },
//     {
//         id: 11,
//         latitude: 43.2800,
//         longitude: 5.3500,
//         image: "img/Imagecolle.png",
//         address: "Rue de la République",
//         city: "Marseille",
//         date: "Ajoutée il y a 10 jours",
//         created_at: new Date("2026-04-22 09:00:00"),
//         quartier: "Joliette",
//         cp: "13002",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 11
//     },
//     {
//         id: 12,
//         latitude: 43.2870,
//         longitude: 5.4100,
//         image: "img/66993195266c203f1e457139.webp",
//         address: "Rue Saint-Ferréol",
//         city: "Marseille",
//         date: "Ajoutée il y a 12 jours",
//         created_at: new Date("2026-04-20 17:00:00"),
//         quartier: "Opéra",
//         cp: "13001",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "REFUSED",
//         user_id: 1
//     },
//     {
//         id: 13,
//         latitude: 43.2950,
//         longitude: 5.3900,
//         image: "img/rennes_boites_a_cles_sur_le_mobilier_urbain_large.jpg.webp",
//         address: "Boulevard Chave",
//         city: "Marseille",
//         date: "Ajoutée il y a 3 semaines",
//         created_at: new Date("2026-04-15 16:00:00"),
//         quartier: "Camas",
//         cp: "13005",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 1
//     },
//     {
//         id: 14,
//         latitude: 43.2400,
//         longitude: 5.3700,
//         image: "img/66993195266c203f1e457139.webp",
//         address: "Traverse de la Gaye",
//         city: "Marseille",
//         date: "Ajoutée il y a 4 jours",
//         created_at: new Date("2026-05-01 19:00:00"),
//         quartier: "Sainte-Marguerite",
//         cp: "13009",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 14
//     },
//     {
//         id: 15,
//         latitude: 43.3200,
//         longitude: 5.3900,
//         image: "img/Imagecolle.png",
//         address: "Rue Loubon",
//         city: "Marseille",
//         date: "Ajoutée il y a 6 jours",
//         created_at: new Date("2026-04-28 14:15:00"),
//         quartier: "Belle de Mai",
//         cp: "13003",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 15
//     },
//     {
//         id: 16,
//         latitude: 43.2920,
//         longitude: 5.3600,
//         image: "img/66993195266c203f1e457139.webp",
//         address: "Quai du Port",
//         city: "Marseille",
//         date: "Ajoutée il y a 9 jours",
//         created_at: new Date("2026-04-23 11:00:00"),
//         quartier: "Vieux-Port",
//         cp: "13002",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 16
//     },
//     {
//         id: 17,
//         latitude: 43.283329,
//         longitude: 5.56667,
//         image: "img/Imagecolle.png",
//         address: "Avenue Antide Boyer",
//         city: "Aubagne",
//         date: "Ajoutée il y a 1 semaine",
//         created_at: new Date("2026-04-26 10:30:00"),
//         quartier: "Centre",
//         cp: "13400",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 17
//     },
//     {
//         id: 18,
//         latitude: 43.4080,
//         longitude: 5.0550,
//         image: "img/rennes_boites_a_cles_sur_le_mobilier_urbain_large.jpg.webp",
//         address: "Rue Lamartine",
//         city: "Martigues",
//         date: "Ajoutée il y a 5 jours",
//         created_at: new Date("2026-04-30 09:20:00"),
//         quartier: "Ferrières",
//         cp: "13500",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "PENDING",
//         user_id: 18
//     },
//     {
//         id: 19,
//         latitude: 43.5283,
//         longitude: 5.4497,
//         image: "img/66993195266c203f1e457139.webp",
//         address: "Rue Gaston de Saporta",
//         city: "Aix-en-Provence",
//         date: "Ajoutée il y a 2 semaines",
//         created_at: new Date("2026-04-18 15:45:00"),
//         quartier: "Centre Historique",
//         cp: "13100",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 1
//     },
//     {
//         id: 20,
//         latitude: 43.4170,
//         longitude: 5.2140,
//         image: "img/Imagecolle.png",
//         address: "Boulevard de l'Europe",
//         city: "Vitrolles",
//         date: "Ajoutée il y a 3 jours",
//         created_at: new Date("2026-05-02 13:30:00"),
//         quartier: "Centre",
//         cp: "13127",
//         region: "Bouches-du-Rhône",
//         pays: "FR",
//         status: "VALIDATED",
//         user_id: 20
//     }
// ];